# Alacritty
# https://alacritty.org
# https://alacritty.org/config-alacritty.html

#
# About the issues on Windows, I got some information from: https://github.com/alacritty/alacritty/pull/6994
# That said:
#  Alacritty on Windows is relying on the system libraries by default, but they
#can have known bugs. For example, your mouse might not work in vim on Windows
#10, even though the issue has long been fixed in Windows 11.
#The solution is to copy files named `conpty.dll` and `OpenConsole.exe` to the
#directory containing the Alacritty executable or to a directory in `PATH`.
#Those files can be found e.g. in WezTerm. They can also be built from the
#Windows Terminal source.
#
# xcopy /F /Y   "C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\Terminal\ServiceHub\os64\conpty.dll"  %HOME%\libin\ProgramFiles\alacritty\ 
# xcopy /F /Y   "C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\Terminal\ServiceHub\os64\OpenConsole.exe"  %HOME%\libin\ProgramFiles\alacritty\ 
#

###########
# GENERAL #
###########

# Import additional configuration files
#import = [
#  '~/.config/alacritty/colors/light.toml'
#]

# Shell program and its arguments
# Default for Linux/BSD/macOS is $SHELL or user's login shell
# Default for Windows is "powershell"
#[shell]
#program = "C:\\Program Files\\Git\\bin\\bash.exe"
#args = ['--login', '-i']

# Working directory
working_directory = "None"  # Default: "None"

# Live config reload (changes require restart)
live_config_reload = true  # Default: true

# Offer IPC using alacritty msg (unix only)
#ipc_socket = true  # Default: true

#######
# ENV #
#######

#[env]
# Environment variables
#TERM = "xterm-256color"

##########
# WINDOW #
##########

[window]
# Startup mode
startup_mode = "Windowed"  # Default: "Windowed"
# Window title
title = "Alacritty"  # Default: "Alacritty"
# Dynamic title
dynamic_title = true  # Default: true
# Window class (Linux/BSD only)
class = { instance = "Alacritty", general = "Alacritty" }  # Default: instance = "Alacritty", general = "Alacritty"
# Decorations theme variant
decorations_theme_variant = "None"  # Default: "None"
# Window dimensions
dimensions = { columns = 0, lines = 0 }  # Default: columns = 0, lines = 0
# Window startup position
position = "None"  # Default: "None"
# Padding
padding = { x = 12, y = 12 }  # Default: x = 0, y = 0
# Dynamic padding
dynamic_padding = true # Default: false
# Window decorations
#decorations = "Buttonless"  # Default: "Full"
# Opacity
opacity = 1.0  # Default: 1.0
# Blur (macOS/KDE Wayland only)
blur = false  # Default: false
# Resize increments
resize_increments = false  # Default: false
# Option as Alt (macOS only)
#option_as_alt = "None"  # Default: "None"

#############
# SCROLLING #
#############

[scrolling]
# Maximum number of lines in the scrollback buffer
history = 10000  # Default: 10000
# Number of lines scrolled for every input scroll increment
multiplier = 1  # Default: 3

########
# FONT #
########

[font]
# Normal font style
normal = { family = "Inconsolata", style = "Regular" }  # Default for Linux/BSD: "monospace", Regular
# Bold font style
bold = { style = "Bold" }  # Inherits family from normal, Default style: Bold
# Italic font style
italic = { style = "Italic" }  # Inherits family from normal, Default style: Italic
# Bold Italic font style
bold_italic = { style = "Bold Italic" }  # Inherits family from normal, Default style: Bold Italic
# Font size in points
size = 16  # Default: 11.25
# Offset is extra space around each character
offset = { x = 0, y = 0 }  # Default: x = 0, y = 0
# Glyph offset determines the locations of the glyphs within their cells
glyph_offset = { x = 0, y = 0 }  # Default: x = 0, y = 0
# Use built-in font for box drawing characters
builtin_box_drawing = true  # Default: true

##########
# COLORS #
##########

[colors]
# Transparent background colors
transparent_background_colors = false  # Default
# Draw bold text with bright colors
draw_bold_text_with_bright_colors = false  # Default

# Primary colors
[colors.primary]
#foreground = "#d8d8d8"  # Default
#background = "#181818"  # Default
#dim_foreground = "#828482"  # Default
#bright_foreground = "None"  # Default

# Cursor colors
[colors.cursor]
#text = "CellBackground"  # Default
#cursor = "CellForeground"  # Default
cursor = "#5fd7af"

# Vi mode cursor colors
[colors.vi_mode_cursor]
#text = "CellBackground"  # Default
#cursor = "CellForeground"  # Default

# Search colors
[colors.search.matches]
#foreground = "#181818"  # Default
#background = "#ac4242"  # Default

[colors.search.focused_match]
#foreground = "#181818"  # Default
#background = "#f4bf75"  # Default

# Hint colors
[colors.hints.start]
#foreground = "#181818"  # Default
#background = "#f4bf75"  # Default

[colors.hints.end]
#foreground = "#181818"  # Default
#background = "#ac4242"  # Default

# Line indicator colors
[colors.line_indicator]
#foreground = "None"  # Default
#background = "None"  # Default

# Footer bar colors
[colors.footer_bar]
#foreground = "#181818"  # Default
#background = "#d8d8d8"  # Default

# Selection colors
[colors.selection]
#text = "CellBackground"  # Default
#background = "CellForeground"  # Default

# Normal colors
[colors.normal]
#black = "#181818"  # Default
#red = "#ac4242"  # Default
#green = "#90a959"  # Default
#yellow = "#f4bf75"  # Default
#blue = "#6a9fb5"  # Default
#magenta = "#aa759f"  # Default
#cyan = "#75b5aa"  # Default
#white = "#d8d8d8"  # Default
#black = "#111213"
#red = "#bb443a"
#green = "#8ea77b"
#yellow = "#d4bf7e"
#blue = "#8ba3b3"
#magenta = "#aa92ad"
#cyan = "#85b3b3"
#white = "#d7d5cf"

# Bright colors
[colors.bright]
#black = "#6b6b6b"  # Default
#red = "#c55555"  # Default
#green = "#aac474"  # Default
#yellow = "#feca88"  # Default
#blue = "#82b8c8"  # Default
#magenta = "#c28cb8"  # Default
#cyan = "#93d3c3"  # Default
#white = "#f8f8f8"  # Default

# Dim colors
[colors.dim]
#black = "#0f0f0f"  # Default
#red = "#712b2b"  # Default
#green = "#5f6f3a"  # Default
#yellow = "#a17e4d"  # Default
#blue = "#456877"  # Default
#magenta = "#704d68"  # Default
#cyan = "#4d7770"  # Default
#white = "#8e8e8e"  # Default


########
# BELL #
########

[bell]
# Visual bell animation effect
animation = "Linear"  # Default: "Linear"
# Duration of the visual bell flash in milliseconds
duration = 0  # Default: 0
# Visual bell animation color
color = "#ffffff"  # Default: "#ffffff"
# Command executed when the bell is rung
command = {program = 'osascript', args = ['-e', 'beep']}  # Default: "None"

#############
# SELECTION #
#############

[selection]
# Characters that are used as separators for "semantic words" in Alacritty
semantic_escape_chars = ",│`|:\"' ()[]{}<>\\t"  # Default: ",│`|:\"' ()[]{}<>\\t"
# When set to true, selected text will be copied to the primary clipboard
save_to_clipboard = true # Default: false

##########
# CURSOR #
##########
[cursor]
# Cursor style
style = { shape = "Block", blinking = "Never" }  # Default: shape = "Block", blinking = "Off"
# Vi mode cursor style (falls back to the active value of the normal cursor if "None")
vi_mode_style = "None"  # Default: "None"
# Cursor blinking interval in milliseconds
blink_interval = 750  # Default: 750
# Time after which cursor stops blinking, in seconds
blink_timeout = 0  # Default: 5
# When true, the cursor will be rendered as a hollow box when the window is not focused
unfocused_hollow = true  # Default: true
# Thickness of the cursor relative to the cell width
thickness = 0.15  # Default: 0.15

############
# TERMINAL #
############

[terminal]
# Controls the OSC 52 behavior for clipboard interactions
osc52 = "CopyPaste"  # Default: "OnlyCopy"

#########
# MOUSE #
#########

[mouse]
# When true, the cursor is temporarily hidden when typing
hide_when_typing = true  # Default: false
# Mouse bindings (actual bindings need to be defined as per user preference)
# Example: bindings = [{ mouse = "Left", action = "Paste" }]
bindings = []

#########
# HINTS #
#########

[hints]
# Define the keys used for hint labels
alphabet = "jfkdls;ahgurieowpq"  # Default: "jfkdls;ahgurieowpq"

# Enable specific hints
#[[hints.enabled]]
# Example configuration (actual settings to be defined based on user preference)
# regex = "..."
# hyperlinks = true
# post_processing = true
# persist = false
# action = "..."
# command = "..."
# binding = { key = "...", mods = "...", mode = "..." }
# mouse = { mods = "...", enabled = true }

# KEYBOARD section of Alacritty configuration
[keyboard]
# Define keyboard bindings here
# Example placeholder (actual bindings need to be defined based on user preference)
bindings = [
    { key = "n", mods = "Control|Shift", action = "CreateNewWindow" },
    { key = "p", mods = "Control|Shift", action = "SpawnNewInstance" },
    { key = "Up", mods = "Control|Shift", action = "ScrollLineUp" },
    { key = "Down", mods = "Control|Shift", action = "ScrollLineDown" },
    { key = "F", mods = "Control|Shift", action = "ToggleFullScreen" },
    { key = "A", mods = "Control|Shift", action = "ToggleViMode" },
    # { key = "Key", mods = "Modifiers", chars = "Characters to send" },
    # ...
]
